name: webinar
description: cognistar project.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.1.5 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: any

  flutter_svg: ^2.0.7
  provider: ^6.1.1
  dio: ^5.2.1+1
  persian_number_utility: ^1.1.3
  file_picker: ^10.1.2
  shared_preferences: ^2.1.2
  loading_indicator: ^3.1.0
  get_it: ^8.0.3
  flutter_advanced_drawer: ^1.3.5
  flutter_rating_bar: ^4.0.1
  google_sign_in: ^6.2.1
  url_launcher: ^6.1.12
  add_2_calendar: ^3.0.1
  http: ^1.1.2
  flutter_widget_from_html: ^0.16.0
  video_player: ^2.8.6
  share_plus: ^11.0.0
  permission_handler: ^12.0.0+1
  path_provider: ^2.1.0
  open_file: ^3.3.0
  flutter_image_compress: ^2.0.4
  image_picker: ^1.0.7
  flutter_slidable: ^4.0.0
  webview_flutter: ^4.4.2
  pod_player: ^0.2.2
  flutter_tts: ^4.0.2
  table_calendar: ^3.0.9
  confetti: ^0.8.0
  animated_flip_counter: ^0.3.4
  fl_chart: ^0.71.0
  syncfusion_flutter_pdfviewer: ^29.1.39
  timezone: ^0.10.0
  flutter_inappwebview: ^6.0.0
  lottie: ^3.0.0
  shimmer: ^3.0.0
  firebase_messaging: ^15.2.5
  flutter_local_notifications: ^19.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^6.0.3
  cached_network_image: ^3.3.1
  fluttertoast: ^8.2.8
  flutter_pdfview: ^1.3.4
  flutter_barcode_scanner: ^2.0.0
  uni_links: ^0.5.1
  firebase_auth: ^5.5.2
  flutter_secure_storage: ^9.2.2
  google_nav_bar: ^5.0.7
  iconly: ^1.0.1
  flutter_iconly: ^1.0.2
  screen_protector: ^1.4.2+1
  flutter_spinkit: ^5.2.1
  flutter_speed_dial: ^7.0.0
  font_awesome_flutter: ^10.8.0
  google_fonts: ^6.2.1
  in_app_purchase: ^3.2.1
  
dependency_overrides:
  flutter_inappwebview_android:
    git:
      url: https://github.com/holzgeist/flutter_inappwebview
      path: flutter_inappwebview_android
      ref: d89b1d32638b49dfc58c4b7c84153be0c269d057

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.9



# The following section is specific to Flutter packages.
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:

    - assets/image/flags/
    - assets/image/png/
    - assets/image/svg/
    - assets/image/json/
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Vazir-Bold
      fonts:
        - asset: assets/font/vazir-bold.ttf
    - family: Tajawal-Medium
      fonts:
        - asset: assets/font/Tajawal-Medium.ttf

    
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
